spring:
  application:
    name: inditradApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/commodity_desk
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
  default-flat-param-object: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: false